import type { Entry, Source, Scheme } from '$lib/core/model';
import sourceData from '../../../content/sources.json';
import schemeData from '../../../content/schemes.json';
import siteData from '../../../content/site.json';
// Generated by the content gate. Draft records never enter the client bundle.
// The predev/prebuild content gate validates schemas and references before bundling.
import published from '../../../.generated/catalog.json';
const records = published;
export const entries = (Object.values(records) as Entry[])
	.filter((e) => e.status !== 'draft')
	.sort((a, b) => {
		if (a.temporal.type === 'undated' || b.temporal.type === 'undated')
			return (
				Number(a.temporal.type === 'undated') - Number(b.temporal.type === 'undated') ||
				a.id.localeCompare(b.id)
			);
		const da = a.temporal.type === 'point' ? a.temporal.date : a.temporal.start;
		const db = b.temporal.type === 'point' ? b.temporal.date : b.temporal.start;
		return (
			da.year - db.year ||
			(da.month ?? 1) - (db.month ?? 1) ||
			(da.day ?? 1) - (db.day ?? 1) ||
			b.importance - a.importance ||
			a.id.localeCompare(b.id)
		);
	});
export const sources: Record<string, Source> = sourceData;
export const schemeLabels: Record<Scheme, string> = schemeData;
export const site = siteData;
export const byId = new Map(entries.map((e) => [e.id, e]));
